FROM python:3.12-slim
LABEL authors="Alexander Vinogradov"

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем requirements.txt и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файл сервера
COPY mcp_server.py .

# Указываем команду для запуска сервера
CMD ["uvicorn", "mcp_server:app", "--host", "0.0.0.0", "--port", "8000"]