FROM python:3.12-slim
LABEL authors="Alexander Vinogradov"

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем requirements.txt и устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем файл клиента
COPY mcp_client.py .

# Указываем команду для запуска клиента
CMD ["python", "mcp_client.py"]